frontend_deck_keeper_index:
    pattern:    /
    defaults:   { _controller: RiceDeckKeeperBundle:Default:index }

frontend_deck_keeper_card:
    pattern:    /card/{slug}
    defaults:   { _controller: RiceDeckKeeperBundle:Default:card }

frontend_deck_keeper_cardset_index:
    pattern:    /sets
    defaults:   { _controller: RiceDeckKeeperBundle:CardSet:index }
