frontend_deck_keeper_index:
    pattern:    /{_locale}
    defaults:   { _controller: RiceDeckKeeperBundle:Default:index, _locale: en }

frontend_deck_keeper_card:
    pattern:    /{_locale}/card/{slug}
    defaults:   { _controller: RiceDeckKeeperBundle:Default:card, _locale: en }

frontend_deck_keeper_cardset_index:
    pattern:    /{_locale}/sets
    defaults:   { _controller: RiceDeckKeeperBundle:CardSet:index, _locale: en }
